USE treinamento;

--a
SELECT P.NMPRODUCT, COUNT(PR.CDPRODUCT) AS 'Total de Pedidos'
FROM PRODUCT AS P
LEFT JOIN PRODUCTREQUEST AS PR
ON (P.CDPRODUCT = PR.CDPRODUCT) GROUP BY P.NMPRODUCT;

--b
SELECT S.NMSUPPLIER, COUNT(P.CDPRODUCT) AS 'Produtos Fornecidos'
FROM SUPPLIER AS S
LEFT JOIN PRODUCT AS P
ON (P.CDSUPPLIER = S.CDSUPPLIER) GROUP BY S.NMSUPPLIER;

--c
SELECT 
	ISNULL (S.NMSUPPLIER, 'Total') AS NMSUPPLIER, 
	ISNULL (P.NMPRODUCT, '') AS NMPRODUCT, SUM(PR.QTAMOUNT) AS TotalProdutosVendidos
FROM 
	PRODUCTREQUEST AS PR
	INNER JOIN PRODUCT AS P
	ON (PR.CDPRODUCT = P.CDPRODUCT)
	INNER JOIN SUPPLIER AS S
	ON (P.CDSUPPLIER = S.CDSUPPLIER)
GROUP BY
	ROLLUP(S.NMSUPPLIER, P.NMPRODUCT)

--d
SELECT
	ISNULL (C.NMCUSTOMER, 'Total') AS NMCUSTOMER, 
	ISNULL (P.NMPRODUCT, 'SubTotal') AS NMPRODUC,
	SUM(QTAMOUNT*PR.VLUNITARY) AS 'TOTALGASTO'
FROM
	PRODUCTREQUEST AS PR
	INNER JOIN PRODUCT AS P
	ON (PR.CDPRODUCT = P.CDPRODUCT)
	INNER JOIN CUSTOMER AS C
	ON (P.CDSUPPLIER = C.CDCUSTOMER)
GROUP BY
	ROLLUP(C.NMCUSTOMER, P.NMPRODUCT);
--e
SELECT C.NMCUSTOMER, C.IDFONE
FROM PRODUCTREQUEST AS PR
RIGHT JOIN PRODUCT AS P
ON (PR.CDPRODUCT = P.CDPRODUCT)
INNER JOIN REQUEST AS R
ON (PR.CDREQUEST = R.CDREQUEST)
INNER JOIN CUSTOMER C
ON (R.CDCUSTOMER = C.CDCUSTOMER)
GROUP BY C.NMCUSTOMER, C.IDFONE, PR.CDPRODUCT HAVING PR.CDPRODUCT  IS NULL;

--f
SELECT S.NMSUPPLIER, S.IDFONE
FROM SUPPLIER AS S
INNER JOIN PRODUCT AS P
ON (S.CDSUPPLIER = P.CDSUPPLIER) WHERE P.NMPRODUCT = 'leite em po' OR P.NMPRODUCT = 'agua mineral';

--g
 SELECT P.NMPRODUCT, S.NMSUPPLIER
 FROM SUPPLIER AS S
 INNER JOIN PRODUCT AS P
 ON(S.CDSUPPLIER = P.CDSUPPLIER)
 INNER JOIN PRODUCTREQUEST AS PR
 ON (P.CDPRODUCT = PR.CDPRODUCT) GROUP BY P.NMPRODUCT, S.NMSUPPLIER HAVING COUNT(PR.CDPRODUCT)>3;

