USE treinamento;

SELECT NMCUSTOMER,IDFONE FROM CUSTOMER WHERE IDFONE LIKE '4%'; 

SELECT * FROM CUSTOMER WHERE IDFONE = NULL;

SELECT NMSUPPLIER,IDFONE FROM SUPPLIER WHERE IDFONE NOT LIKE '(%'; 

SELECT NMPRODUCT, QTSTOCK, VLPRICE, VLPRICE*0.9 AS DESCONTO FROM PRODUCT WHERE QTSTOCK>2000;

SELECT NMPRODUCT, VLPRICE FROM PRODUCT WHERE VLPRICE BETWEEN 10 AND 20;

SELECT NMPRODUCT, VLPRICE, VLPRICE*QTSTOCK AS TOTAL_ESTOQUE fROM PRODUCT WHERE VLPRICE>50;

SELECT PRODUCT.NMPRODUCT AS PRODUTO, SUPPLIER.NMSUPPLIER AS FORNECEDOR, SUPPLIER.IDFONE AS FONE FROM SUPPLIER
INNER JOIN PRODUCT
ON (SUPPLIER.CDSUPPLIER = PRODUCT.CDSUPPLIER) WHERE VLPRICE>20 AND QTSTOCK>1500;

SELECT CUSTOMER.NMCUSTOMER AS CLIENTE, REQUEST.DTREQUEST AS DATA_PEDIDO, REQUEST.VLTOTAL AS VALOR_TOTAL FROM CUSTOMER
INNER JOIN REQUEST
ON (CUSTOMER.CDCUSTOMER = REQUEST.CDCUSTOMER) WHERE DTREQUEST BETWEEN '20030601'AND '20030731';

SELECT C.NMCUSTOMER, P.NMPRODUCT, R.DTREQUEST, PR.QTAMOUNT, PR.VLUNITARY, R.VLTOTAL 
FROM PRODUCTREQUEST AS PR
INNER JOIN REQUEST AS R 
ON (PR.CDREQUEST= R.CDREQUEST)
INNER JOIN PRODUCT AS P
ON (PR.CDPRODUCT = P.CDPRODUCT)
INNER JOIN CUSTOMER AS C
ON (R.CDCUSTOMER = C.CDCUSTOMER) WHERE QTAMOUNT>500;
