USE treinamento;

--a
SELECT DISTINCT P.NMPRODUCT FROM PRODUCT AS P
INNER JOIN PRODUCTREQUEST AS PR
ON (P.CDPRODUCT = PR.CDPRODUCT);

SELECT DISTINCT P.NMPRODUCT FROM PRODUCT AS P
INNER JOIN PRODUCTREQUEST AS PR
ON (P.CDPRODUCT = PR.CDPRODUCT) GROUP BY P.NMPRODUCT;

--b
SELECT P.NMPRODUCT, COUNT(PR.CDPRODUCT) AS 'Número de x que o produto foi pedido', SUM(PR.QTAMOUNT) AS 'Quantidade Total Pedida'
FROM PRODUCTREQUEST AS PR
INNER JOIN PRODUCT AS P
ON (PR.CDPRODUCT = P.CDPRODUCT)
INNER JOIN REQUEST AS R
ON (PR.CDREQUEST = R.CDREQUEST) GROUP BY P.NMPRODUCT

--c
SELECT S.NMSUPPLIER, SUM(P.QTSTOCK), AVG(P.VLPRICE) AS 'MÉDIA DE PREÇO DOS PRODUTOS', COUNT(P.CDPRODUCT) AS 'QT de Produtos fornecidos'
FROM PRODUCT AS P
INNER JOIN SUPPLIER AS S
ON(P.CDSUPPLIER = S.CDSUPPLIER) GROUP BY S.NMSUPPLIER;

--d
SELECT C.NMCUSTOMER, C.IDFONE, MAX(PR.QTAMOUNT*PR.VLUNITARY) AS 'Maior Compra', MIN(PR.QTAMOUNT*PR.VLUNITARY) AS 'Menor Compra', 
SUM(PR.QTAMOUNT*PR.VLUNITARY) AS 'Total Comprado', AVG(PR.QTAMOUNT*PR.VLUNITARY) AS 'Média do Valor Comprado'
FROM PRODUCTREQUEST AS PR
INNER JOIN REQUEST AS R
ON (PR.CDREQUEST = R.CDREQUEST)
INNER JOIN CUSTOMER AS C
ON (R.CDCUSTOMER = C.CDCUSTOMER) GROUP BY C.NMCUSTOMER, c.IDFONE ORDER BY 'Maior Compra' DESC;

--e
SELECT R.DTREQUEST, C.NMCUSTOMER, COUNT(DISTINCT PR.CDPRODUCT) AS 'Produtos', PR.QTAMOUNT*PR.VLUNITARY AS 'Valor Total do Pedido', AVG(PR.VLUNITARY) AS 'Média dos valores do pedido'
FROM PRODUCTREQUEST AS PR
INNER JOIN PRODUCT AS P
ON PR.CDPRODUCT=P.CDPRODUCT
INNER JOIN REQUEST AS R
ON (PR.CDREQUEST = R.CDREQUEST)
INNER JOIN CUSTOMER C
ON (R.CDCUSTOMER = C.CDCUSTOMER) GROUP BY R.DTREQUEST, C.NMCUSTOMER, PR.QTAMOUNT, PR.VLUNITARY ORDER BY 'Produtos';

--f
SELECT S.NMSUPPLIER, COUNT(P.CDPRODUCT) AS QTPRODUTOS
FROM PRODUCT AS P
INNER JOIN SUPPLIER S
ON (P.CDSUPPLIER = S.CDSUPPLIER) GROUP BY S.NMSUPPLIER HAVING COUNT(P.CDPRODUCT)>1;

--g
SELECT P.NMPRODUCT, COUNT(PR.CDPRODUCT) AS 'Pedidos', PR.QTAMOUNT
FROM PRODUCTREQUEST AS PR
INNER JOIN PRODUCT AS P
ON (PR.CDPRODUCT = P.CDPRODUCT) GROUP BY P.NMPRODUCT, PR.QTAMOUNT HAVING COUNT(PR.CDPRODUCT)>5

--h
SELECT C.NMCUSTOMER, P.NMPRODUCT, P.VLPRICE, COUNT(PR.CDPRODUCT) AS QTPedidos, S.NMSUPPLIER
FROM PRODUCTREQUEST AS PR
INNER JOIN PRODUCT AS P
ON (PR.CDPRODUCT = P.CDPRODUCT)
INNER JOIN SUPPLIER AS S
ON (P.CDSUPPLIER = S.CDSUPPLIER)
INNER JOIN REQUEST AS R
ON (PR.CDREQUEST = R.CDREQUEST)
INNER JOIN CUSTOMER AS C
ON (R.CDCUSTOMER = C.CDCUSTOMER) GROUP BY C.NMCUSTOMER, P.NMPRODUCT, P.VLPRICE, S.NMSUPPLIER, R.VLTOTAL HAVING R.VLTOTAL>1000 ORDER BY C.NMCUSTOMER;