USE treinamento;

--a
SELECT P.NMPRODUCT, S.NMSUPPLIER, P.VLPRICE, P.VLPRICE*0.9 AS '10% de Desconto', P.VLPRICE*0.8 AS '20% de Desconto', P.VLPRICE*0.7 AS '30% de Desconto'
FROM PRODUCT AS P
INNER JOIN SUPPLIER S
ON (P.CDSUPPLIER = S.CDSUPPLIER) WHERE (VLPRICE*0.9)>15 ORDER BY P.NMPRODUCT;

SELECT P.NMPRODUCT, S.NMSUPPLIER, P.VLPRICE, P.VLPRICE*0.9 AS '10% de Desconto', P.VLPRICE*0.8 AS '20% de Desconto', P.VLPRICE*0.7 AS '30% de Desconto'
FROM PRODUCT AS P
INNER JOIN SUPPLIER S
ON (P.CDSUPPLIER = S.CDSUPPLIER) WHERE (VLPRICE*0.9)>15 ORDER BY P.VLPRICE;

-- b
SELECT P.NMPRODUCT, S.NMSUPPLIER, P.VLPRICE, (P.VLPRICE*P.QTSTOCK) AS VLTOTAL, (P.VLPRICE*2*P.QTSTOCK) AS 'VLTOTAL - Dobro do estoque'
FROM PRODUCT AS P
INNER JOIN SUPPLIER S
ON (P.CDSUPPLIER = S.CDSUPPLIER) WHERE  (P.VLPRICE*P.QTSTOCK)> 12000 ORDER BY S.NMSUPPLIER

SELECT P.NMPRODUCT, S.NMSUPPLIER, P.VLPRICE, (P.VLPRICE*P.QTSTOCK) AS VLTOTAL, (P.VLPRICE*2*P.QTSTOCK) AS 'VLTOTAL - Dobro do estoque'
FROM PRODUCT AS P
INNER JOIN SUPPLIER S
ON (P.CDSUPPLIER = S.CDSUPPLIER) WHERE  (P.VLPRICE*P.QTSTOCK)> 12000 ORDER BY P.NMPRODUCT;

--c
SELECT * FROM CUSTOMER WHERE NMCUSTOMER LIKE 'J%' AND IDFONE IS NOT NULL ORDER BY NMCUSTOMER;

--d
SELECT P.NMPRODUCT, P.VLPRICE, S.NMSUPPLIER
FROM PRODUCT AS P
INNER JOIN SUPPLIER S
ON (P.CDSUPPLIER = S.CDSUPPLIER) WHERE S.NMSUPPLIER LIKE '_ica%' ORDER BY S.NMSUPPLIER

SELECT P.NMPRODUCT, P.VLPRICE, S.NMSUPPLIER
FROM PRODUCT AS P
INNER JOIN SUPPLIER AS S
ON (P.CDSUPPLIER = S.CDSUPPLIER) WHERE S.NMSUPPLIER LIKE '_ica%' ORDER BY P.VLPRICE;

--e
SELECT P.NMPRODUCT, S.NMSUPPLIER, S.IDFONE,(P.VLPRICE*P.QTSTOCK) AS VLTOTAL
FROM SUPPLIER AS S
INNER JOIN PRODUCT AS P
ON (S.CDSUPPLIER = P.CDSUPPLIER) WHERE P.NMPRODUCT LIKE 'S%' AND P.VLPRICE>50 ORDER BY S.NMSUPPLIER;

SELECT P.NMPRODUCT, S.NMSUPPLIER, S.IDFONE,(P.VLPRICE*P.QTSTOCK) AS VLTOTAL
FROM SUPPLIER AS S
INNER JOIN PRODUCT AS P
ON (S.CDSUPPLIER = P.CDSUPPLIER) WHERE P.NMPRODUCT LIKE 'S%' AND P.VLPRICE>50 ORDER BY P.VLPRICE;

--f
SELECT C.NMCUSTOMER, P.NMPRODUCT, R.DTREQUEST, R.DTDELIVER, PR.QTAMOUNT, PR.VLUNITARY, (PR.QTAMOUNT*PR.VLUNITARY) AS VLTOTAL
FROM PRODUCTREQUEST AS PR
INNER JOIN REQUEST AS R
ON (PR.CDREQUEST = R.CDREQUEST)
INNER JOIN PRODUCT AS P
ON (PR.CDPRODUCT = P.CDPRODUCT)
INNER JOIN CUSTOMER AS C
ON (R.CDCUSTOMER = C.CDCUSTOMER) WHERE QTAMOUNT<600 AND R.DTREQUEST BETWEEN '20030801'AND '20030831' AND P.NMPRODUCT LIKE 'M%';

--g
SELECT C.NMCUSTOMER, P.NMPRODUCT, S.NMSUPPLIER, R.DTREQUEST, R.DTDELIVER, P.VLPRICE
FROM REQUEST AS R
INNER JOIN PRODUCTREQUEST AS PR
ON (PR.CDREQUEST = R.CDREQUEST)
INNER JOIN CUSTOMER C
ON (C.CDCUSTOMER = R.CDCUSTOMER)
INNER JOIN PRODUCT AS P
ON (PR.CDPRODUCT = P.CDPRODUCT)
INNER JOIN SUPPLIER AS S
ON (P.CDSUPPLIER = S.CDSUPPLIER) WHERE S.IDFONE LIKE '(011%' AND VLPRICE>20; 