--USE treinamento;

--1a
DELETE FROM CUSTOMER WHERE NOT EXISTS (SELECT CDCUSTOMER FROM REQUEST);

--1b
DELETE FROM SUPPLIER WHERE NOT IN (SELECT CDSUPPLIER FROM PRODUCT);

--1c
UPDATE PRODUCTREQUEST SET VLUNITARY = VLPRICE FROM PRODUCT AS P INNER JOIN PRODUCTREQUEST AS PR ON (P.CDPRODUCT = PR.CDPRODUCT);

 --1d
ALTER TABLE SUPPLIER
ADD DSSTATUS VARCHAR(10);
 --1e
UPDATE SUPPLIER SET DSSTATUS = 'INATIVO'
WHERE CDSUPPLIER NOT IN (SELECT P.CDSUPPLIER 
							FROM PRODUCT AS P
							INNER JOIN SUPPLIER AS S
							ON (P.CDSUPPLIER = S.CDSUPPLIER)
						);

--1f
UPDATE CUSTOMER SET NMADRESS = 'DESCONHECIDO' 
WHERE NMADRESS IS NULL;

--1g
INSERT INTO PRODUCTREQUEST (CDREQUEST, CDPRODUCT, QTAMOUNT, VLUNITARY)
SELECT DISTINCT R.CDREQUEST, P.CDPRODUCT, '10', P.VLPRICE FROM PRODUCT AS P
INNER JOIN PRODUCTREQUEST AS PR
ON (P.CDPRODUCT = PR.CDPRODUCT)
INNER JOIN REQUEST AS R
ON (PR.CDREQUEST = R.CDREQUEST) WHERE P.CDPRODUCT NOT IN (SELECT PR.CDPRODUCT FROM PRODUCTREQUEST PR WHERE PR.CDREQUEST = R.CDREQUEST);


--2a
SELECT P.NMPRODUCT, C.NMCUSTOMER, COUNT(PR.CDPRODUCT) AS QTPEDIDOS , SUM(PR.QTAMOUNT) AS QTCOMPRADA, COUNT(PR.CDPRODUCT)*(PR.VLUNITARY*PR.QTAMOUNT) AS VLTOTALPAGO
FROM PRODUCT AS P
INNER JOIN PRODUCTREQUEST AS PR
ON (P.CDPRODUCT = PR.CDPRODUCT) 
INNER JOIN REQUEST AS R
ON (PR.CDREQUEST = R.CDREQUEST)
INNER JOIN CUSTOMER AS C
ON (R.CDCUSTOMER = C.CDCUSTOMER) 
GROUP BY P.NMPRODUCT, C.NMCUSTOMER, PR.VLUNITARY, PR.QTAMOUNT

--2b
SELECT C.NMCUSTOMER, COUNT(R.CDREQUEST) AS NBPEDIDOS, SUM(R.VLTOTAL)  AS VLTOTAL
FROM REQUEST AS R
INNER JOIN CUSTOMER AS C
ON (R.CDCUSTOMER = C.CDCUSTOMER) WHERE R.DTREQUEST BETWEEN '20030101'AND '20031231'
GROUP BY C.NMCUSTOMER;

--2c
SELECT S.NMSUPPLIER, S.IDFONE, P.NMPRODUCT, P.VLPRICE, P.QTSTOCK 
FROM SUPPLIER AS S
LEFT JOIN PRODUCT AS P
ON (S.CDSUPPLIER = P.CDSUPPLIER);

--2d
SELECT C.NMCUSTOMER, R.DTREQUEST, R.VLTOTAL
FROM CUSTOMER AS C
LEFT JOIN REQUEST AS R
ON (C.CDCUSTOMER = R.CDCUSTOMER);


