USE Exercicio1

CREATE TABLE CUSTOMER(
CDCUSTOMER SMALLINT NOT NULL,	
NMCUSTOMER VARCHAR(50) NOT NULL,
NRFONE VARCHAR(14),
DSADRESS VARCHAR(100),
)

CREATE TABLE SUPPLIER(
CDSUPPLIER SMALLINT NOT NULL,
NMSUPPLIER VARCHAR(50),
NRFONE VARCHAR(14)
)

CREATE TABLE REQUEST(
CDREQUEST SMALLINT NOT NULL,
DTREQUEST DATETIME,
DTDELIVER DATE,
VLTOTAL SMALLINT
)

CREATE TABLE PRODUCT(
CDPRODUCT SMALLINT NOT NULL,
NMPRODUCT VARCHAR(50),
VLPRICE SMALLINT,
QTSTOCK SMALLINT
)

CREATE TABLE PRODUCTREQUEST(
CDREQUEST SMALLINT NOT NULL,
CDPRODUCT SMALLINT,
QTAMOUNT SMALLINT,
VLUNITARY SMALLINT
)

ALTER TABLE CUSTOMER
ADD PRIMARY KEY(CDCUSTOMER);

ALTER TABLE PRODUCT
ADD PRIMARY KEY(CDPRODUCT);

ALTER TABLE REQUEST
ADD PRIMARY KEY(CDREQUEST);

ALTER TABLE SUPPLIER
ADD PRIMARY KEY(CDSUPPLIER);

ALTER TABLE REQUEST
ADD CDCUSTOMER SMALLINT NOT NULL
CONSTRAINT fk_CDCUSTOMER FOREIGN KEY (CDCUSTOMER) REFERENCES CUSTOMER;

ALTER TABLE PRODUCT
ADD CDSUPPLIER SMALLINT NOT NULL
CONSTRAINT fk_CDSUPPLIER FOREIGN KEY (CDSUPPLIER) REFERENCES SUPPLIER;

ALTER TABLE PRODUCTREQUEST
ADD CDREQUEST SMALLINT NOT NULL
CONSTRAINT fk_CDREQUEST FOREIGN KEY (CDREQUEST) REFERENCES REQUEST;

ALTER TABLE PRODUCTREQUEST
ADD CDPRODUCT SMALLINT NOT NULL
CONSTRAINT fk_CDPRODUCT FOREIGN KEY (CDPRODUCT) REFERENCES PRODUCT;

ALTER TABLE PRODUCTREQUEST
ADD PRIMARY KEY (CDREQUEST, CDPRODUCT);

CREATE INDEX indice_CDSUPPLIER
ON PRODUCT (CDSUPPLIER);

CREATE INDEX indice_CDCUSTOMER
ON REQUEST (CDCUSTOMER);

ALTER TABLE SUPPLIER
ADD DSADRESS VARCHAR(100);

--Inseri o valor 1 para CDCUSTOMER, pois esqueci de fazer essa coluna como Identity. Pesquisei como fazer isso e aparentemente tem que deletar a coluna e inseri-lá novamente.
INSERT INTO CUSTOMER (CDCUSTOMER, NMCUSTOMER, NRFONE, DSADRESS) VALUES (1, 'Fabiano','99879375','Rua Tijucas, 110, Centro, Joinville – S.C');

INSERT INTO REQUEST (CDREQUEST, DTREQUEST, DTDELIVER, VLTOTAL, CDCUSTOMER) VALUES (23, '20080131', '20080205', 54, 1); 

UPDATE CUSTOMER SET NRFONE = '99012567' WHERE CDCUSTOMER = 1;

DELETE FROM CUSTOMER WHERE NRFONE = '99012567';

DELETE FROM REQUEST;
DELETE FROM CUSTOMER;

SELECT * FROM CUSTOMER;
SELECT * FROM REQUEST;


DROP TABLE PRODUCTREQUEST;
DROP TABLE PRODUCT, REQUEST;
DROP TABLE CUSTOMER, SUPPLIER;